### ISSUE TITLE
genCountMatrixFromVcf fails with phased genotypes

### ISSUE THREAD

**Issue by lbeltrame** [rvalieris/signeR#11]
That's because they're expressed as "0|1" and not "0/1" in the VCF, causing splitting to fail.

**Comment by rvalieris** [comment]
thanks for the report.
I assume these phased genotypes can used in the same way as the unphased genotypes or do they need some special treatment ?, I mean besides the delimiter being different.

**Comment by lbeltrame** [comment]
I don't work much with phased genotypes, in fact I think this was an exception in the data I had: for now I just "unphased" them following advice from https://www.biostars.org/p/269854/ and then I ran the analysis again.

**Comment by lbeltrame** [comment]
For a definition of phased vs unphased: https://www.biostars.org/p/7846/ (IOW, phased genotypes hold haplotype information; unphased don't).

**Comment by rvalieris** [comment]
alright, thanks for the links. yeah I don't think signeR could make use haplotype info, so I will just add `|` as a possible delimiter for the GT field.

**Comment by rvalieris** [comment]
fixed on https://github.com/rvalieris/signeR/commit/788141209eac35ef6c8a90621487a72fdb9db50b
