### ISSUE TITLE
Method to get reconstructed tri-nt probs & exposures

### ISSUE THREAD

**Issue by itsvenu** [rvalieris/signeR#16]
Hi,

Thanks for the interesting package.

I was just wondering is there a method to get reconstructed tri-nucleotide probability matrix and exposure (raw & normalized fractions) of each signature for each sample. I'd use probability matrix to compute cosine similarity b/w extracted signatures and known signatures. This will help us assigning biological implication of the signatures.

Should I simply use,

`signeR_obj$SignExposures@Psummary ` and `Esummary`?

Thank you.

**Comment by rvalieris** [comment]
Hello,

to compute cosine similarity you can use the medians.

`Median_exp(signeR_obj$SignExposures)` will return a exposure matrix of signatures x samples.
`Median_sign(signeR_obj$SignExposures)` will return a signatures matrix of 96 tri-nt x signatures.

`@Psummary` and `@Esummary` are just pre-computed quantiles for the plots error bars.

**Comment by itsvenu** [comment]
Ah, great. Thanks @rvalieris.
