### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by nurmians** [rvalieris/signeR#18]
Would it be too much trouble to give a short description of what signeR does on the github page?

Inputs? Outputs? I'm just trying to figure out if it can do what I'm looking for. It is a lot of trouble to go through installation for a quick look, and I just found out I can't even read the html documentation on the server where I need to run it. =P

**Comment by rvalieris** [comment]
hello,

the [vignette](http://bioconductor.org/packages/release/bioc/vignettes/signeR/inst/doc/signeR-vignette.html) has all the instructions and examples.

are you having trouble accessing the vignette ?
