### ISSUE TITLE
Opportunity matrix for non-human organism

### ISSUE THREAD

**Issue by tamaraprieto** [rvalieris/signeR#20]
Hi, 

I am trying to extract signatures from tumors of a non-model organism. I obtained the SNV mutation matrix but I am struggling to create the opportunity matrix. The VCFs are too long and too many to load them in R so I had to built the SNV matrix myself and I wanted to do the same with the opportunity matrix. If the experiment implied WGS, should I give the same frequency for the 96 trinucleotides motifs for all the samples?I would really appreciate you could explain to me in more detail how this opportunity matrix should look like for a whole-genome experiment. 

Thanks

**Comment by rvalieris** [comment]
hello, can you give some more details ?
- do you have a reference genome for your organism ?
-> the function `genOpportunityFromGenome` can generate the opportunity matrix from a fasta and a bed file of regions.
- is there enough coverage for the entire genome ?
-> its not uncommon for some parts of the genome to not have enough coverage for variant calling, the purporse of the bed file is to count only the regions that were used for calling variants.

you can see an example for the opportunity here: https://github.com/rvalieris/signeR/blob/master/inst/extdata/21_breast_cancers.opportunity.txt
it has the same dimensions of the count matrix, each column is the number of the respective trinucleotides present in the genome(considering only the regions of the bed), each row is a sample, usually every row is going to have the same information, unless you have some extra CNV data per sample, which would allow you to count duplicate or deleted regions of each sample accordingly.

finally, if you don't have a reference genome, or if for some reason generating the opportunity is not possible you can just run signeR without the `Opport=` argument, which will default to equal weights for all 96 trinucleotides.

**Comment by tamaraprieto** [comment]
Thank you very much. 
Yes, I have a reference genome. The clarification about the bed file was very useful, I thought it was only for WES experiments but now I understand I should create a bed file of the regions with enough coverage to call variants. 
Just a last question, do you count the trinucleotides in overlapping or non-overlapping windows?I guess overlapping, but just wanted to make sure.

**Comment by rvalieris** [comment]
yes, and ideally you should apply a similar coverage filter for your variants, to make sure the count matrix was generated only from variants in the regions counted in the opportunity.

yes it overlaps by 1 base, so the sequence ACTGAC counts ACT, CTG, TGA, GAC.

just be careful to have the columns in the same order as your count matrix.

**Comment by tamaraprieto** [comment]
Thank you so much!
