### ISSUE TITLE
Apply on a single vcf file with multiple samples

### ISSUE THREAD

**Issue by xiw588** [rvalieris/signeR#21]
Hi, I want to apply this function on a large vcf file with multiple samples. Is there any way that I can easily do this? 

Here I attached the colData output as below. So basically I have 646 samples in total in a large vcf file.

vcfobj@colData
DataFrame with 646 rows and 1 column
          Samples
        <integer>
DN768           1
DF-2884         2
DF-1655         3
DN357           4
DN1400          5
...           ...
DF-3781       642
DF-3744       643
DF-3766       644
DF-3735       645
DF-3760       646

Thank you.

**Comment by rvalieris** [comment]
hello, you can split the vcf into multiple parts and process them in parallel, see this example: 
https://gist.github.com/rvalieris/e8dc4c40068a6593f1f4bb19e41ad50c

adjust the number of cores and chunk size according with your case.

**Comment by xiw588** [comment]
Thanks!
