### ISSUE TITLE
Error of running genCountMatrixFromVcf()

### ISSUE THREAD

**Issue by xiw588** [rvalieris/signeR#22]
Hi I tried to apply genCountMatrixFromVcf() on a test set of vcf file, but got the following error messages. Can you help me fix this issue? 

Thank you. 

Best regards,

Error in .getOneSeqFromBSgenomeMultipleSequences(x, name, start, NA, width,  : 
  sequence 1 not found
In addition: Warning messages:
1: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
2: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
3: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

**Comment by rvalieris** [comment]
hello, most likely the BSgenome you are using is not correct. the chromosome names in the BSgenome need to match the chromosome names in the vcf.

**Comment by xiw588** [comment]
I solved this issue! Thank you! I have a followup question, I want to apply the function in different subset of samples. Do you know if there is any way that I could add a covariate to subset in signeR? Thank you

**Comment by rvalieris** [comment]
which function ? the signeR function that fits the data only considers the counts matrix and the opportunity matrix. you can run all subsets together and explore the difference between groups with  DiffExp (differential exposure analysis), see the vignette: https://www.bioconductor.org/packages/release/bioc/vignettes/signeR/inst/doc/signeR-vignette.html
