### ISSUE TITLE
Estimating exposures from known signatures

### ISSUE THREAD

**Issue by khuhu** [rvalieris/signeR#31]
Hi,

I saw in the vignette there was a functionality for estimating exposures based on a given signature matrix, but it seems the signeR function no longer takes the variables fixedP and P. Is there still a way to perform the analysis, or another function for it?

Best,
Kevin

**Comment by rvalieris** [comment]
hello, sorry for the delay.

can you clarify which version of signeR you are using ? we recently released a 2.0.0 version and the parameters fixedP and P are supported there.

**Comment by khuhu** [comment]
No worries. I used devtools to download the 2.0 version and it works. I had another question, how does parallelization work for the signeR function?

**Comment by rvalieris** [comment]
signeR is using the future library: https://future.futureverse.org/
you can set a [plan](https://future.futureverse.org/reference/plan.html) before calling the signeR function to change the parameters signeR will use.
