### ISSUE TITLE
How to use signeR with non-human reference genome?

### ISSUE THREAD

**Issue by tobsecret** [rvalieris/signeR#4]
I want to estimate signatures for VCFs I have for a non-human species. How do I have to prepare the reference in order to  be able to follow section `3.1: Input from VCF`? 

```
library(VariantAnnotation)

# BSgenome, equivalent to the one used on the variant call
library(BSgenome.Hsapiens.UCSC.hg19)

vcfobj <- readVcf("/path/to/a/file.vcf", "hg19")
mut <- genCountMatrixFromVcf(BSgenome.Hsapiens.UCSC.hg19, vcfobj)
```
When you are calling `readVcf`, what is the `"hg19"` in case I am using a non-standard reference genome?
Similarly I am wondering how I can prepare an alternate to `BSgenome.Hsapiens.UCSC.hg19` that works for the purposes of the `genCountMatrixFromVcf` function. Now the BSgenome docs mention that they are Biostrings objects but I have no idea what that entails and am quite frankly not proficient in the R bioconductor ecosystem in the slightest. Do I need annotations or is just the raw sequence fine?

**Comment by rvalieris** [comment]
hello,

this is tricky, I haven't tried to do this yet, but there is a guide on how to make a BSgenome of a new reference, however it might be too complicated, as its intended for devs to create new BSgenome packages: https://www.bioconductor.org/packages/devel/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf

the other option would be to adapt the signeR functions (genCount and genOpportunity) to run without BSgenome, no annotation is required, we only need the reference to count the triplet context of the mutations.

I will see if I can make a separated versions of these functions that don't need a BSgenome, but for now [checkout the code](https://github.com/rvalieris/signeR/blob/master/R/genMatrix.R), the BSgenome is only necessary for the generation of the matrices (count and opportunity), so if you could make a separated script that generates them you wouldn't need a BSgenome for the later parts.

**Comment by tobsecret** [comment]
Thanks, I stumbled upon the BSgenome docs after the fact, too (because the docs to `BSgenome.Hsapiens.UCSC.hg19` didn't have those instructions) and I actually think this should be doable. I did at the time also inspect the vcfobj function which seems to be just calling a function called getSeq or something similar. The problem is that that function's description wasn't entirely obvious to me, as "hg19" does not seem to be a valid input for any of the arguments the function takes but I it might just be because I am not familiar with the R nomenclature. 
I just have very little time to work on this, so figured it would be more efficient to ask someone with tons of experience. 
Thanks for your reply!

**Comment by rvalieris** [comment]
actually, this was easier than I anticipated.

you can load your genome from the fasta like this, it should work as long as the contigs on the vcf match the fasta:
```
library(Biostrings)
myfasta = readDNAStringSet("custom.fasta")

vcfobj = readVcf("/path/to/a/file.vcf")
mut = genCountMatrixFromVcf(myfasta, vcfobj)
```

for the opportunity matrix I had to [change the function a little](https://gist.github.com/rvalieris/a51af3a7dc82d972a0228f321b2411d8) to work with the fasta:
```
source("gen_mat.R")
opp = genOpportunityFromFasta(myfasta, target_regions)
```

hope that helps.

**Comment by tobsecret** [comment]
Thank you so much! Will try it out on the weekend.

**Comment by tobsecret** [comment]
So I tried it and on 6 CPUs and 100 GB of RAM, `genCountMatrixFromVcf` failed to process a 559173 line VCF with 194 samples (so 205 columns) in 10 hours - is that expected?

**Comment by rvalieris** [comment]
I am sorry, this must be frustrating, definitely not expected.
failed in what way ? is there a error message ?

if you tried with the fasta, also try 
```
myfasta = FaFile("custom.fasta")
````

just make sure you have a `.fai` file together with the fasta.

**Comment by tobsecret** [comment]
Failed in that it didn't finish and the task at hand really doesn't seem like it would require that much processing power for so long, so I suspect something else is up - was just wondering if you had experienced something like this in the past. Will try using FaFile.

**Comment by rvalieris** [comment]
so it still running then ? I admit that the code on genCountMatrixFromVcf is not very optimized... FaFile should help if your genome is very big because of the index, but if it still running I would keep the current process going concurrently as it is.

**Comment by tobsecret** [comment]
I stopped it because I was pretty sure something was up. The genome also has a lot of contigs, another potential reason for why it might have taken so long. Will try out FaFile and report back. Thanks so much for helping me out!

**Comment by rvalieris** [comment]
I made some substantial optimizations on the function, its not released on the package yet but you can use [this script](https://gist.github.com/rvalieris/7cd695c7d63c62ef852a4536c7c7902d)

turns out it was spending a lot of unnecessary time converting strings inside the loop

**Comment by tobsecret** [comment]
Oh, wow - that's awesome! Will try it out when I need it next - at the moment my jobs are still running but I think it's working. That is because a job I ran yesterday, using your FaFile trick finished with an error message only for a line of code downstream of `genCountMatrixFromVcf(myfasta, vcfobj)`, so it seems that part worked. I fixed that line now and the job is currently running.
