### ISSUE TITLE
Get array of Z matrix samples

### ISSUE THREAD

**Issue by wir963** [rvalieris/signeR#5]
Hey, 

I really enjoyed your paper in Bioinformatics and would like to use your tool. Specifcally, I would like to be able to access the array of Z (mutations to mutation signatures assignments) matrix samples similar to how I can access the arrays of E and P using the Exp and Sign object fields of the SignExp class.

Is there any existing way to access this data using the R package?

**Comment by rvalieris** [comment]
hello,
sorry, currently we don't store the Z anywhere on the object so it can't be accessed after the calculation is done, we would have to change the code to do that.

**Comment by wir963** [comment]
Okay, thanks for getting to back to me and letting me know!
