### ISSUE TITLE
How to use signeR with VCF when VCF file only supports one sample?

### ISSUE THREAD

**Issue by hermidalc** [rvalieris/signeR#6]
New user here, been struggling with the signeR instructions on how to generate the count matrix using VCF.  In your tutorial you only import one VCF file, which from my understanding of VCF format each file can only be for a single sample.  How does one get it to work with multiple VCFs and how will signeR then know which mutations belong to which samples?

Maybe an easier solution for me would be to drop using VCF.  Do you know of any code which can take a standard ICGC tab-delimited simple somatic mutations file and convert it to the signeR tab-delimited input file format?

**Comment by rvalieris** [comment]
Hello,

a VCF with a single sample will generate a matrix with a single row. you can then concatenate multiple rows together to make a single count matrix of all samples.

here is some example code:
```R
m = matrix(ncol=96,nrow=0)
for(i in vcf_files) {
    vo = readVcf(i, "hg19")
    # sample name (should pick up from the vcf automatically if available)
    # colnames(vo) = i
    m0 = genCountMatrixFromVcf(mygenome, vo)
    m = rbind(m, m0)
}
dim(m)
```

input from other sources are possible, but will need to write a converter for it, see the vcf converter source code as an example: https://github.com/rvalieris/signeR/blob/master/R/genMatrix.R#L72

**Comment by hermidalc** [comment]
@rvalieris thank you for the assistance!  I might suggest you add something like what you wrote to your docs to make it clearer how to work with VCFs.

**Comment by rvalieris** [comment]
yes that's a good idea. I will add some extra docs in the next release.
