### ISSUE TITLE
DiffExp:  Error in plot.window(...) : need finite 'ylim' values

### ISSUE THREAD

**Issue by tobsecret** [rvalieris/signeR#7]
Have been trying to use DiffExp but been running into the `Error in plot.window(...) : need finite 'ylim' values`. Initially I thought it might be because of empty strings in the character vector I provided but it didn't seem to what caused it. Do you have an idea what might be the problem?

```R
load("genSignatures_2_20_pfalciparum_2640_isolates_long_run.RData")
country_df = read.csv('./cleaned_country_info_for_samples.txt')
diff_exposure <- DiffExp(signatures$SignExposures, labels=as.character(as.vector(country_df$country)))
Error in plot.window(...) : need finite 'ylim' values
```

[cleaned_country_info_for_samples.txt](https://github.com/rvalieris/signeR/files/2673518/cleaned_country_info_for_samples.txt)
[genSignatures_2_20_pfalciparum_2640_isolates_long_run.RData](https://www.filehosting.org/file/details/770334/genSignatures_2_20_pfalciparum_2640_isolates_long_run.RData)

**Comment by tobsecret** [comment]
So it seems it has to do with these three lines:
https://github.com/rvalieris/signeR/blob/86ca84c3c97ea7b384eb24d324bd82c6a0b02e9f/R/SignExp.R#L870
```
Pval[,k]<-sapply(1:n,function(s){
                Test<-method(as.vector(Exposure[s,used]),used_labels,...)
                return(Test$p.value)
            })
```       
https://github.com/rvalieris/signeR/blob/86ca84c3c97ea7b384eb24d324bd82c6a0b02e9f/R/SignExp.R#L883
```
Lpval <- -1*log(Pval) #n x r
rownames(Lpval)<-paste("S",1:n,sep="")
y.min<-min(Lpval); y.max<-max(Lpval)
```

https://github.com/rvalieris/signeR/blob/86ca84c3c97ea7b384eb24d324bd82c6a0b02e9f/R/SignExp.R#L950

```
plot(1:n,rep(lcut,n),type="n",main="",xlab="",ylab="-log(pvalue)",
xlim=c(0.5,n+0.5),ylim=c(y.min,y.max),xaxt="n",cex.lab=1.2)
```

So if the Pvalue is 0, then the log is undefined and that's why it throws an error?

**Comment by rvalieris** [comment]
Thanks for the report. this is a bug.

if Pvalue is 0 its log is -Inf and -1*log(Pval) = Inf. The problem here is setting Inf as the upper limit for the y axis.

Replacing the line

`y.min<-min(Lpval); y.max<-max(Lpval)`

with

`y.min<-min(Lpval); y.max<-max(Lpval[Lpval<Inf])`

should fix the problem, however note that the boxplot won't show up on the plot because Inf will not be plotted.

We will include this correction on signeR's next version, thank you.

Regards,
R.

**Comment by tobsecret** [comment]
Thanks @rvalieris!
