### ISSUE TITLE
Cannot find function "genCountMatrixFromVcf"

### ISSUE THREAD

**Issue by craigdj91** [rvalieris/signeR#8]
Hello, I keep getting the following error message:

> mut <- genCountMatrixFromVcf(BSgenome.Hsapiens.UCSC.hg19, vcfobj)

Error in genCountMatrixFromVcf(BSgenome.Hsapiens.UCSC.hg19, vcfobj) : 
  could not find function "genCountMatrixFromVcf"

I have very limited experience with R, so I thought I would ask.

Thanks!

**Comment by rvalieris** [comment]
Hello, 
make sure the signeR package is loaded. and check the version with the sessionInfo() function.

**Comment by craigdj91** [comment]
Thanks Renan! The R version wasn't compatible, so I updated; it works now.
