### ISSUE TITLE
How are variant frequencies accounted for when calculating signatures?

### ISSUE THREAD

**Issue by craigdj91** [rvalieris/signeR#9]
How are variant frequencies incorporated into the signature calculation. For example, if there are two samples with similar mutation types, but drastically different frequencies, how is that accounted for?

I'm assessing low-frequency variants <5% using error-correction methods like UMI, so I have variant frequencies ranging from 0.01% to 5% and I want to ensure that that the low-frequency variants don't get thrown away in the calculation

**Comment by rvalieris** [comment]
Hello,

the variant frequencies are not considered in the signature discovery phase of the method.
whether they will be included or not depends on how the count matrix is generated. if you are using the  genCountMatrixFromVcf method, all variants with an alternative allele (on the GT field) will be included in the resulting matrix, its up to the user to filter undesirable variants before this step.
